version: '3'
services:
  wordpress:
    depends_on:
      - database
    image: wordpress:6.3.0-php8.2-fpm #wordpress:6.3.0-php8.2-fpm #  wordpress:6.3.0-php8.2-apache  https://hub.docker.com/_/wordpress
    restart: unless-stopped
    ports:
      - 9000:9000 #- 9000:9000  # without nginx - 80:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306 # use the same name as database service
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wordpress:/var/www/html/
    networks:
      - wordpress-network

  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './wordpress:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - ./logs/nginx:/var/log/nginx
    networks:
      - wordpress-network
   
  database:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2048m
    networks:
      - wordpress-network

#  database:
#    image: mysql
#    restart: unless-stopped
#    env_file: .env
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
#      MYSQL_DATABASE: '${MYSQL_DATABASE}'
#      MYSQL_USER: '${MYSQL_USER}'
#      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
#    volumes:
#      - db-data_msql:/var/lib/mysql
#    networks:
#      - wordpress-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress-network      

volumes:
#  db-data_msql:
  db-data:
  wordpress:

networks:
  wordpress-network:
    driver: bridge  